keys:
  - &host_cx22 age14zz02243lgzkzx7mtyr6kxspt7p8qhals3vc9keqc7lgalmjcqkqhuvat8
  - &user_sid age19yeqvv28fgrtk6jsh3xyaf0lch86kna6rcz4dwe962yyyyevu30sx474xy
creation_rules:
  - path_regex: hosts/cx22/secrets.yaml$
    key_groups:
    - age:
      - *host_cx22
      - *user_sid
