keys:
  - &host_cx22 age1xgvksumx8d43tuet5lsjrvtwstm30p9njwyjr03g46dsgr5d7gfsk23qkh
  - &user_sid age19yeqvv28fgrtk6jsh3xyaf0lch86kna6rcz4dwe962yyyyevu30sx474xy
creation_rules:
  - path_regex: hosts/cx22/secrets.yaml$
    key_groups:
    - age:
      - *host_cx22
      - *user_sid
